[package]
name = "raspi_backend"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = {version = "0.11.10", features = ["blocking"]}
base64 = "0.13.0"
chrono = "0.4"
rand = "*"
